# Generated by Django 5.2.16 on 2026-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_workflow'),
        ('employees', '0005_announcement_audience_targeting'),
        ('organization', '0001_enterprise_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('all', 'All staff'), ('department', 'Selected department(s)'), ('branch', 'Selected branch(es)'), ('cadre', 'Selected cadre(s)')], db_index=True, default='all', help_text='Who should receive this announcement.', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='cadres',
            field=models.ManyToManyField(blank=True, help_text='Job titles / cadres (e.g. Manager, Officer).', related_name='announcements', to='employees.designation'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='employees.department'),
        ),
    ]
