# Generated by Django 5.0.14 on 2026-07-22 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_branches_and_docs_perm'),
        ('organization', '0001_enterprise_upgrade'),
        ('recruitment', '0001_enterprise_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('detail', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'application activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Visible only to recruiters/HR.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('skills', 'Skills test'), ('psychometric', 'Psychometric'), ('case_study', 'Case study'), ('assignment', 'Take-home assignment'), ('other', 'Other')], default='skills', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('max_score', models.DecimalField(decimal_places=1, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('expired', 'Expired'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('result_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.PositiveSmallIntegerField(default=0)),
                ('communication', models.PositiveSmallIntegerField(default=0)),
                ('cultural_fit', models.PositiveSmallIntegerField(default=0)),
                ('problem_solving', models.PositiveSmallIntegerField(default=0)),
                ('overall', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, choices=[('strong_hire', 'Strong hire'), ('hire', 'Hire'), ('maybe', 'Maybe'), ('no_hire', 'No hire'), ('strong_no', 'Strong no')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('positions', models.PositiveSmallIntegerField(default=1)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Internship')], default='full_time', max_length=20)),
                ('justification', models.TextField(help_text='Business case for this hire.')),
                ('job_description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('is_replacement', models.BooleanField(default=False)),
                ('replacement_for', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_hr', 'Pending HR'), ('pending_gm', 'Pending GM'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='draft', max_length=20)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.CharField(blank=True, max_length=255)),
                ('gm_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('gm_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_name', models.CharField(max_length=120)),
                ('referee_title', models.CharField(blank=True, max_length=120)),
                ('referee_company', models.CharField(blank=True, max_length=150)),
                ('referee_email', models.EmailField(blank=True, max_length=254)),
                ('referee_phone', models.CharField(blank=True, max_length=30)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('contacted_at', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('would_rehire', models.BooleanField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-posted_date', '-created_at'], 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='current_employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='current_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='referral_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('careers', 'Careers portal'), ('internal', 'Internal / referral'), ('linkedin', 'LinkedIn'), ('job_board', 'Job board'), ('agency', 'Recruitment agency'), ('walk_in', 'Walk-in'), ('other', 'Other'), ('manual', 'Added by HR')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('onsite', 'On-site'), ('panel', 'Panel'), ('technical', 'Technical'), ('hr', 'HR'), ('final', 'Final / leadership')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('strong_hire', 'Strong hire'), ('hire', 'Hire'), ('maybe', 'Maybe'), ('no_hire', 'No hire'), ('strong_no', 'Strong no')], max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='benefits_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='offer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='probation_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='responded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='Visible to employees.'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible on careers portal.'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='show_salary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Applied'), ('screening', 'Screening'), ('phone_screen', 'Phone screen'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('reference_check', 'Reference check'), ('offer', 'Offer'), ('offer_accepted', 'Offer accepted'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='issued_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On hold'), ('closed', 'Closed'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('vacancy', 'email'), name='uniq_application_vacancy_email'),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewscorecard',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='recruitment.interview'),
        ),
        migrations.AddField(
            model_name='interviewscorecard',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to='employees.department'),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='gm_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_reviewed_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='hr_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='recruitment.jobrequisition'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interviewscorecard',
            unique_together={('interview', 'reviewer')},
        ),
    ]
