# Generated by Django 5.0.14 on 2026-08-13 03:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _backfill_course_codes(apps, schema_editor):
    Course = apps.get_model("training", "Course")
    for course in Course.objects.all():
        if course.code:
            continue
        base = "".join(c for c in (course.title or "CRS").upper() if c.isalnum())[:8] or "CRS"
        course.code = f"{base}-{course.pk:04d}"
        course.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_announcement_audience_targeting'),
        ('organization', '0001_enterprise_upgrade'),
        ('training', '0001_enterprise_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('max_level', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'training categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('bank_details', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='trainingcertificate',
            options={'ordering': ['-issued_date', '-version']},
        ),
        migrations.AlterModelOptions(
            name='trainingenrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingschedule',
            options={'ordering': ['-start_date'], 'verbose_name': 'training session', 'verbose_name_plural': 'training sessions'},
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_validity_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank = does not expire', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.RunPython(_backfill_course_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_method',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('virtual', 'Virtual (Teams / Zoom / Meet)'), ('elearning', 'E-learning (self-paced)'), ('ojt', 'On-the-Job Training'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('coaching', 'Coaching'), ('mentoring', 'Mentoring'), ('blended', 'Blended')], default='classroom', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='issues_certificate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='require_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='require_full_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='training_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('certification', 'Certification'), ('apprenticeship', 'Apprenticeship'), ('mandatory', 'Mandatory / Compliance'), ('development', 'Development')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='verification_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='waitlist_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='meeting_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='title',
            field=models.CharField(blank=True, help_text='Optional session title override', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingcertificate',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.trainingenrollment'),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='evaluation_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended'), ('completed', 'Completed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='employees.designation')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('pre', 'Pre-assessment'), ('post', 'Post-assessment'), ('practical', 'Practical'), ('final', 'Final examination')], default='final', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training.trainingenrollment')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employment_type', models.CharField(blank=True, max_length=30)),
                ('apply_on_hire', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='training.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.designation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.trainingcategory'),
        ),
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('brochure', 'Brochure'), ('material', 'Training Material'), ('presentation', 'Presentation'), ('manual', 'Manual'), ('assessment', 'Assessment'), ('certificate', 'Certificate'), ('attendance', 'Attendance Sheet'), ('invoice', 'Invoice'), ('evaluation', 'Evaluation Report'), ('other', 'Other')], default='material', max_length=30)),
                ('file', models.FileField(upload_to='training_docs/')),
                ('is_public_to_learners', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.course')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.trainingschedule')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_quality', models.PositiveSmallIntegerField(default=3)),
                ('course_content', models.PositiveSmallIntegerField(default=3)),
                ('materials', models.PositiveSmallIntegerField(default=3)),
                ('venue', models.PositiveSmallIntegerField(default=3)),
                ('relevance', models.PositiveSmallIntegerField(default=3)),
                ('practical_usefulness', models.PositiveSmallIntegerField(default=3)),
                ('overall', models.PositiveSmallIntegerField(default=3)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='training.trainingenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('course_fee', 'Course Fee'), ('instructor', 'Instructor Fee'), ('venue', 'Venue'), ('accommodation', 'Accommodation'), ('transport', 'Transportation'), ('meals', 'Meals'), ('materials', 'Materials'), ('certification', 'Certification'), ('other', 'Other')], default='course_fee', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('incurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='training.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.department')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='training.trainingschedule')),
            ],
            options={
                'ordering': ['-incurred_on'],
            },
        ),
        migrations.CreateModel(
            name='TrainingInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('instructor_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_instructor_profiles', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='default_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.traininginstructor'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.traininginstructor'),
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('competency_gap', 'Competency Gap'), ('performance', 'Performance Review'), ('mandatory', 'Mandatory Requirement'), ('manager', 'Manager Request'), ('employee', 'Employee Request'), ('onboarding', 'Onboarding')], default='competency_gap', max_length=30)),
                ('required_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap', models.PositiveSmallIntegerField(default=0)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='training.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='employees.employee')),
                ('recommended_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='training.course')),
            ],
            options={
                'ordering': ['-gap', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='provider_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.trainingprovider'),
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField()),
                ('expected_benefit', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='training_requests/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('hr_review', 'HR Review'), ('finance_review', 'Finance Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('current_step', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='training.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ld_training_requests', to='employees.employee')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='training.trainingschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='training.trainingrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('develops_to_level', models.PositiveSmallIntegerField(default=3)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='training.competency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_links', to='training.course')),
            ],
            options={
                'unique_together': {('course', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('assessed_at', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='manual / training / performance', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_levels', to='training.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'employee competencies',
                'unique_together': {('employee', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_links', to='training.course')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='training.learningpath')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('path', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PositionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField(default=3)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_requirements', to='training.competency')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_competencies', to='employees.designation')),
            ],
            options={
                'verbose_name_plural': 'position competencies',
                'unique_together': {('designation', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='assigned', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='employees.employee')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='training.trainingenrollment')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='training.trainingassignmentrule')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['employee', 'course', 'status'], name='training_tr_employe_8156ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('mark', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='training.trainingenrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_date'],
                'unique_together': {('enrollment', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='TrainingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_budgets', to='employees.department')),
            ],
            options={
                'ordering': ['-year', 'department__name'],
                'unique_together': {('year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_links', to='training.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='training.trainingprogram')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('program', 'course')},
            },
        ),
    ]
