# Generated by Django 5.0.14 on 2026-07-11 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('certificate', 'Certificate'), ('nda', 'NDA'), ('cv', 'CV'), ('offer_letter', 'Offer Letter'), ('appointment', 'Appointment Letter'), ('warning', 'Warning'), ('promotion', 'Promotion'), ('id', 'Identification'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
