# Generated by Django 5.0.14 on 2026-08-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_enterprise_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Employment Contract'), ('academic', 'Academic Certificate'), ('guarantor', 'Guarantor Form'), ('reference', 'Reference Letter'), ('cv', 'CV / Resume'), ('id', 'Means of Identification'), ('offer_letter', 'Offer Letter'), ('appointment', 'Appointment Letter'), ('certificate', 'Professional Certificate'), ('medical', 'Medical Report'), ('bank', 'Bank Details Form'), ('tax', 'Tax Document'), ('nda', 'NDA'), ('warning', 'Warning'), ('promotion', 'Promotion'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
