# Generated by Django 5.2.7 on 2026-09-04 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_announcement_audience_targeting'),
        ('organization', '0001_enterprise_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('require_manager_approval', models.BooleanField(default=True)),
                ('require_transport_approval', models.BooleanField(default=True)),
                ('require_driver_acceptance', models.BooleanField(default=True)),
                ('allow_carpooling', models.BooleanField(default=True)),
                ('max_route_deviation_percent', models.PositiveSmallIntegerField(default=20)),
                ('geofence_radius_metres', models.PositiveIntegerField(default=100)),
                ('auto_start_enabled', models.BooleanField(default=False)),
                ('auto_arrival_enabled', models.BooleanField(default=False)),
                ('min_booking_notice_hours', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'transportation policies',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=60)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('phone_override', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__user__first_name', 'employee__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('ride_type', models.CharField(choices=[('official', 'Official trip'), ('carpool', 'Carpool'), ('shuttle', 'Shuttle'), ('executive', 'Executive'), ('airport', 'Airport transfer'), ('inter_branch', 'Inter-branch'), ('other', 'Other')], default='official', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('driver_pending', 'Awaiting driver'), ('driver_accepted', 'Driver accepted'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('aborted', 'Aborted')], db_index=True, default='draft', max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('origin_label', models.CharField(max_length=255)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_return', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('current_stage', models.CharField(blank=True, choices=[('manager', 'Department Manager'), ('transport', 'Transport Officer')], max_length=20)),
                ('allow_carpool', models.BooleanField(default=True)),
                ('seats_reserved', models.PositiveSmallIntegerField(default=0, help_text='Confirmed passenger seats currently held.')),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='transport.driver')),
                ('organizer', models.ForeignKey(help_text='Transport officer or employee who owns this ride (not always a passenger).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_organized', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_requested', to='employees.employee')),
            ],
            options={
                'ordering': ['-scheduled_departure', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.ride')),
            ],
            options={
                'ordering': ['ride', 'sequence'],
                'unique_together': {('ride', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_label', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending_approval', 'Pending approval'), ('confirmed', 'Confirmed'), ('boarding', 'Boarding'), ('onboard', 'On board'), ('arrived', 'Arrived'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='requested', max_length=30)),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('arrival_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_participations', to='employees.employee')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='transport.ride')),
                ('stop', models.ForeignKey(blank=True, help_text='Drop-off stop for this passenger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='transport.ridestop')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('ride', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('driver_assigned', 'Driver assigned'), ('driver_accepted', 'Driver accepted'), ('driver_declined', 'Driver declined'), ('passenger_added', 'Passenger added'), ('passenger_removed', 'Passenger removed'), ('join_requested', 'Join requested'), ('join_confirmed', 'Join confirmed'), ('ready', 'Marked ready'), ('started', 'Journey started'), ('stop_arrived', 'Stop arrived'), ('passenger_arrived', 'Passenger arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note', 'Note')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transport.ride')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='transport.ridepassenger')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='transport.ridestop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Toyota Hiace – HQ Shuttle', max_length=120)),
                ('registration_number', models.CharField(max_length=40, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('bus', 'Bus / Hiace'), ('van', 'Van'), ('truck', 'Truck'), ('other', 'Other')], default='bus', max_length=20)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=14, help_text='Maximum passengers (excluding driver).')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('gps_device_id', models.CharField(blank=True, help_text='Optional dedicated tracker ID.', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='organization.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='transport.vehicle'),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('driver_pwa', 'Driver PWA'), ('tracker', 'GPS Tracker'), ('manual', 'Manual')], default='driver_pwa', max_length=20)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='transport.ride')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_drivers', to='transport.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance'), ('roadworthiness', 'Roadworthiness'), ('registration', 'Registration'), ('other', 'Other')], default='other', max_length=40)),
                ('file', models.FileField(blank=True, upload_to='transport/vehicles/%Y/%m/')),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_label', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('organizer_approved', 'Organizer approved'), ('admin_approved', 'Admin approved'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('organizer_approved', models.BooleanField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_admin', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_join_requests', to='employees.employee')),
                ('organizer_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_organizer', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='transport.ride')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ride', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RideApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('manager', 'Department Manager'), ('transport', 'Transport Officer')], max_length=20)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Awaiting action'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='transport.ride')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('ride', 'stage')},
            },
        ),
    ]
