# Generated by Django 5.2.7 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_transport_tms_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route_geometry',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON LineString from the routing provider.'),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
