# Generated by Django 5.2.7 on 2026-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_route_geometry_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the vehicle.', null=True, upload_to='transport/vehicles/photos/%Y/%m/'),
        ),
    ]
