# Generated by Django 5.2.7 on 2026-09-07 01:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_vehicle_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('station', models.CharField(blank=True, max_length=120)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Defaults to litres × price_per_litre when blank.', max_digits=14, null=True)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (km)')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='transport/fuel/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='transport.driver')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries_recorded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='transport.vehicle')),
            ],
            options={
                'verbose_name_plural': 'fuel entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil change'), ('service', 'Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('other', 'Other')], default='service', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('performed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (km)')),
                ('next_due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transport/maintenance/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.vehicle')),
            ],
            options={
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
    ]
