# Generated by Django 5.2.7 on 2026-09-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_fuel_maintenance_phase5'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationpolicy',
            name='estimated_cost_per_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional ₦/km used for estimated trip cost on analytics.', max_digits=12),
        ),
        migrations.AddField(
            model_name='transportationpolicy',
            name='require_cancel_reason_after_approval',
            field=models.BooleanField(default=True, help_text='Require a cancellation reason once a ride is past draft/submitted.'),
        ),
    ]
