from django.urls import path
from . import views

app_name = "training"

urlpatterns = [
    path("", views.dashboard, name="overview"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("catalogue/", views.catalogue, name="catalogue"),
    path("catalogue/new/", views.course_create, name="course_create"),
    path("catalogue/<int:pk>/", views.course_detail, name="course_detail"),
    path("catalogue/<int:pk>/edit/", views.course_edit, name="course_edit"),
    path("catalogue/<int:pk>/lessons/add/", views.lesson_create, name="lesson_create"),
    path("catalogue/<int:pk>/lessons/<int:lesson_id>/delete/", views.lesson_delete, name="lesson_delete"),
    path("catalogue/<int:pk>/watch/", views.watch_course, name="watch_course"),
    path(
        "catalogue/<int:pk>/lessons/<int:lesson_id>/progress/",
        views.lesson_progress,
        name="lesson_progress",
    ),
    path("categories/new/", views.category_create, name="category_create"),
    path("programs/", views.programs, name="programs"),
    path("programs/new/", views.program_create, name="program_create"),
    path("programs/<int:pk>/add-course/", views.program_add_course, name="program_add_course"),
    path("sessions/", views.sessions, name="sessions"),
    path("sessions/new/", views.session_create, name="session_create"),
    path("sessions/<int:pk>/", views.session_detail, name="session_detail"),
    path("enroll/", views.enroll, name="enroll"),
    path("enrollments/<int:enrollment_id>/attendance/", views.mark_attendance, name="mark_attendance"),
    path("enrollments/<int:enrollment_id>/assessment/", views.record_assessment_view, name="record_assessment"),
    path("enrollments/<int:enrollment_id>/complete/", views.complete_enrollment, name="complete_enrollment"),
    path("enrollments/<int:enrollment_id>/evaluate/", views.evaluate_training, name="evaluate"),
    path("my/", views.my_learning, name="my_learning"),
    path("request/", views.request_training, name="request_training"),
    path("approvals/", views.approvals, name="approvals"),
    path("approvals/<int:pk>/decide/", views.approve_request, name="approve_request"),
    path("competencies/", views.competencies, name="competencies"),
    path("competencies/new/", views.competency_create, name="competency_create"),
    path("competencies/position/", views.position_competency_create, name="position_competency_create"),
    path("competencies/employee/", views.employee_competency_set, name="employee_competency_set"),
    path("needs/", views.needs, name="needs"),
    path("needs/scan/", views.scan_gaps, name="scan_gaps"),
    path("certificates/", views.certificates, name="certificates"),
    path("calendar/", views.calendar, name="calendar"),
    path("reports/", views.reports, name="reports"),
    path("providers/", views.providers, name="providers"),
    path("instructors/new/", views.instructor_create, name="instructor_create"),
]
