# Generated by Django 5.0.14 on 2026-07-12 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('hod', 'Head of Department'), ('hr', 'Human Resources'), ('gm', 'General Manager')], default='hod', help_text='Active approval stage while status is pending.', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('hod', 'Head of Department'), ('hr', 'Human Resources'), ('gm', 'General Manager')], max_length=10)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Awaiting action'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_step_actions', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('leave_request', 'stage')},
            },
        ),
    ]
