# Generated by Django 5.0.14 on 2026-06-30 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('hikvision', 'HikVision'), ('zkteco', 'ZKTeco'), ('other', 'Other')], default='hikvision', max_length=20)),
                ('connection_mode', models.CharField(choices=[('pull', 'Pull (Django polls device via ISAPI)'), ('push', 'Push (device posts events to webhook)'), ('both', 'Both')], default='both', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=80)),
                ('username', models.CharField(default='admin', max_length=50)),
                ('password', models.CharField(blank=True, help_text='Stored for ISAPI digest auth pull requests.', max_length=128)),
                ('location', models.CharField(blank=True, help_text='e.g. Main Gate, Floor 3 Entrance', max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('webhook_token', models.CharField(blank=True, help_text='Per-device shared secret for push events.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='ok / error / never', max_length=20)),
                ('last_sync_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend')], default='present', max_length=20)),
                ('source', models.CharField(choices=[('face', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card', 'Card'), ('password', 'Password'), ('manual', 'Manual Entry'), ('webhook', 'Device Webhook')], default='face', max_length=20)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='attendance__date_b73b54_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RawPunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_employee_no', models.CharField(help_text='Raw employeeNoString from device payload.', max_length=50)),
                ('direction', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('source', models.CharField(choices=[('face', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card', 'Card'), ('password', 'Password'), ('manual', 'Manual Entry'), ('webhook', 'Device Webhook')], default='face', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('matched', models.BooleanField(default=False, help_text='Whether device_employee_no matched a known Employee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='attendance.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='attendance__timesta_179d8e_idx'), models.Index(fields=['device_employee_no'], name='attendance__device__c710c4_idx')],
            },
        ),
    ]
