# Generated by Django 5.0.14 on 2026-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='comm_key',
            field=models.PositiveIntegerField(default=0, help_text='ZKTeco communication key / device password (integer). Usually 0 unless changed on the device.'),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='brand',
            field=models.CharField(choices=[('zkteco', 'ZKTeco'), ('hikvision', 'HikVision'), ('other', 'Other')], default='zkteco', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='connection_mode',
            field=models.CharField(choices=[('pull', 'Pull (HRMS polls the device)'), ('push', 'Push (device posts events to webhook)'), ('both', 'Both')], default='pull', max_length=10),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Static LAN IP, e.g. 192.168.1.201'),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='password',
            field=models.CharField(blank=True, help_text='HikVision ISAPI password (Digest auth).', max_length=128),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='port',
            field=models.PositiveIntegerField(default=4370, help_text='ZKTeco TCP COMM port is typically 4370. HikVision ISAPI is usually 80.'),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='username',
            field=models.CharField(blank=True, default='admin', help_text='HikVision ISAPI username', max_length=50),
        ),
    ]
