# Generated by Django 5.0.14 on 2026-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_zkteco_tcp_defaults'),
        ('employees', '0005_announcement_audience_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last successful API heartbeat or punch.', null=True),
        ),
        migrations.AddField(
            model_name='rawpunchlog',
            name='event_id',
            field=models.CharField(blank=True, help_text='Optional vendor/event idempotency key. Prevents duplicate ingest when set.', max_length=120),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card', 'Card'), ('password', 'Password'), ('pin', 'PIN'), ('qr', 'QR Code'), ('manual', 'Manual Entry'), ('webhook', 'Device Webhook'), ('api', 'Device API')], default='face', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Required for pull mode (LAN IP). Optional for remote API / push-only devices.', null=True),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='webhook_token',
            field=models.CharField(blank=True, db_index=True, help_text='Per-device API / webhook secret. Used as Bearer token for remote push.', max_length=64),
        ),
        migrations.AlterField(
            model_name='rawpunchlog',
            name='source',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('fingerprint', 'Fingerprint'), ('card', 'Card'), ('password', 'Password'), ('pin', 'PIN'), ('qr', 'QR Code'), ('manual', 'Manual Entry'), ('webhook', 'Device Webhook'), ('api', 'Device API')], default='face', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rawpunchlog',
            index=models.Index(fields=['event_id'], name='attendance__event_i_a39156_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawpunchlog',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('device', 'event_id'), name='uniq_punch_device_event_id'),
        ),
    ]
