# Generated by Django 5.0.14 on 2026-08-13 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_biometric_remote_api'),
        ('employees', '0005_announcement_audience_targeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('pull_staff', 'Pull staff IDs from device'), ('push_staff', 'Push staff IDs to device'), ('pull_attendance', 'Pull attendance / punches from device'), ('get_info', 'Get device info')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to device'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='attendance.biometricdevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='attendance__device__6dbb74_idx'), models.Index(fields=['-created_at'], name='attendance__created_eaee35_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceStaffSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Device user / biometric ID', max_length=50)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('card_no', models.CharField(blank=True, max_length=40)),
                ('privilege', models.CharField(blank=True, max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_snapshots', to='attendance.biometricdevice')),
                ('linked_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_enrollments', to='employees.employee')),
            ],
            options={
                'ordering': ['staff_id'],
                'indexes': [models.Index(fields=['staff_id'], name='attendance__staff_i_beebc4_idx')],
                'unique_together': {('device', 'staff_id')},
            },
        ),
    ]
