# Generated by Django 5.0.14 on 2026-06-30 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('employees', 'Employees'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('rbac', 'Roles & Permissions'), ('reports', 'Reports'), ('system', 'System')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles (Admin, HR Manager, etc.) cannot be deleted.')),
                ('dashboard_key', models.CharField(default='employee', help_text='Which dashboard template this role lands on, e.g. admin, hr, manager, payroll, employee.', max_length=30)),
                ('color', models.CharField(default='#6366f1', help_text='Badge color for this role.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='rbac_auditl_timesta_704a1f_idx')],
            },
        ),
    ]
