# Generated by Django 5.0.14 on 2026-07-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('employees', 'Employees'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('rbac', 'Roles & Permissions'), ('reports', 'Reports'), ('system', 'System'), ('recruitment', 'Recruitment'), ('performance', 'Performance'), ('training', 'Training'), ('assets', 'Assets'), ('documents', 'Documents'), ('visitors', 'Visitors'), ('organization', 'Organization')], max_length=20),
        ),
    ]
