# Generated by Django 5.0.14 on 2026-07-11 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_enterprise_upgrade'),
        ('organization', '0001_enterprise_upgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default='Nigeria', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employeecertification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeemploymenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeepromotion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepromotion',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='employees.employee'),
        ),
    ]
