# Generated by Django 5.2.16 on 2026-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_branches_and_docs_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='User ID / Employee No. as enrolled on the biometric device (ZKTeco user_id).', max_length=50, null=True, unique=True),
        ),
    ]
