# Generated by Django 5.0.14 on 2026-07-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_enterprise_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('response_detail', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
