from django.urls import path

from . import views

app_name = "transport"

urlpatterns = [
    path("", views.hub, name="hub"),
    path("policy/", views.policy_edit, name="policy"),
    path("schedule/", views.schedule, name="schedule"),
    path("vehicles/", views.vehicle_list, name="vehicles"),
    path("vehicles/new/", views.vehicle_create, name="vehicle_create"),
    path("vehicles/<int:pk>/", views.vehicle_detail, name="vehicle_detail"),
    path("vehicles/<int:pk>/edit/", views.vehicle_edit, name="vehicle_edit"),
    path("vehicles/<int:pk>/documents/", views.vehicle_document_add, name="vehicle_document_add"),
    path("fuel/", views.fuel_list, name="fuel_list"),
    path("fuel/new/", views.fuel_create, name="fuel_create"),
    path("fuel/<int:pk>/delete/", views.fuel_delete, name="fuel_delete"),
    path("maintenance/", views.maintenance_list, name="maintenance_list"),
    path("maintenance/new/", views.maintenance_create, name="maintenance_create"),
    path("maintenance/<int:pk>/delete/", views.maintenance_delete, name="maintenance_delete"),
    path("analytics/", views.transport_analytics, name="analytics"),
    path("drivers/", views.driver_list, name="drivers"),
    path("drivers/new/", views.driver_create, name="driver_create"),
    path("drivers/<int:pk>/edit/", views.driver_edit, name="driver_edit"),
    path("rides/", views.ride_list, name="rides"),
    path("history/", views.transport_history, name="history"),
    path("live/", views.live_map, name="live_map"),
    path("rides/new/", views.ride_create, name="ride_create"),
    path("shuttles/new/", views.shuttle_create, name="shuttle_create"),
    path("api/geocode/", views.api_geocode, name="api_geocode"),
    path("api/route/", views.api_route, name="api_route"),
    path("api/live/", views.api_live_positions, name="api_live"),
    path("api/rides/<int:pk>/location/", views.api_location_ping, name="api_location_ping"),
    path("rides/<int:pk>/", views.ride_detail, name="ride_detail"),
    path("rides/<int:pk>/journey/", views.ride_journey, name="ride_journey"),
    path("api/rides/<int:pk>/journey/", views.api_ride_journey, name="api_ride_journey"),
    path("rides/<int:pk>/submit/", views.ride_submit, name="ride_submit"),
    path("rides/<int:pk>/cancel/", views.ride_cancel, name="ride_cancel"),
    path("rides/<int:pk>/leave/", views.passenger_leave, name="passenger_leave"),
    path("rides/<int:pk>/start/", views.ride_start, name="ride_start"),
    path("rides/<int:pk>/complete/", views.ride_complete, name="ride_complete"),
    path("rides/<int:pk>/passengers/<int:passenger_id>/boarding/", views.passenger_boarding, name="passenger_boarding"),
    path("rides/<int:pk>/passengers/<int:passenger_id>/onboard/", views.passenger_onboard, name="passenger_onboard"),
    path("rides/<int:pk>/passengers/<int:passenger_id>/arrived/", views.passenger_arrived, name="passenger_arrived"),
    path("rides/<int:pk>/join/", views.join_request_create, name="join_request"),
    path("rides/<int:pk>/joins/<int:join_id>/<str:action>/", views.join_request_decide, name="join_decide"),
    path("rides/<int:pk>/review/<str:action>/", views.ride_review, name="ride_review"),
    path("approvals/", views.approvals, name="approvals"),
    path("driver/", views.driver_portal, name="driver_portal"),
    path("driver/rides/<int:pk>/accept/", views.driver_accept_ride, name="driver_accept"),
    path("driver/rides/<int:pk>/decline/", views.driver_decline_ride, name="driver_decline"),
]
